version: '3.8'

services:
  cpu:
    image: ${HOST}/${REPO}:${VERSION}
    build:
      context: .
      dockerfile: Dockerfile.cpu
      #target: app
    container_name: mnist
    entrypoint: python /opt/ml/code/train.py
    environment:
    - MLFLOW_URI=${MLFLOW_URI}


  gpu:
    image: ${HOST}/${REPO}:${VERSION}-gpu
    build:
      context: .
      dockerfile: Dockerfile.gpu
      args:
        GPU_BASE: ${GPU_BASE}
      #target: app
    container_name: mnist
    entrypoint: python /opt/ml/code/train.py
    environment:
    - MLFLOW_URI=${MLFLOW_URI}

