stages:
  combine:
    cmd: python src/combine.py
    deps:
    - data/raw/aclImdb/test/neg
    - data/raw/aclImdb/test/pos
    - data/raw/aclImdb/train/neg
    - data/raw/aclImdb/train/pos
    - src/combine.py
    outs:
    - data/processed/test.jsonl
    - data/processed/train.jsonl
  train:
    cmd: python src/train.py
    deps:
    - data/processed/test.jsonl
    - data/processed/train.jsonl
    - data/raw/glove.6B.50d.txt
    - src/train.py
    outs:
    - models
