stages:
  prepare:
    cmd: python src/prepare_data.py
    deps:
    - data/raw/aclImdb/test/neg
    - data/raw/aclImdb/test/pos
    - data/raw/aclImdb/train/neg
    - data/raw/aclImdb/train/pos
    - src/prepare_data.py
    outs:
    - data/processed/test.jsonl
    - data/processed/train.jsonl
