stages:
  combine:
    cmd: python src/combine.py
    deps:
    - data/raw/aclImdb/test/neg
    - data/raw/aclImdb/test/pos
    - data/raw/aclImdb/train/neg
    - data/raw/aclImdb/train/pos
    - src/combine.py
    outs:
    - data/processed/test.jsonl
    - data/processed/train.jsonl
  prepare:
    cmd: python src/train.py prepare
    deps:
    - data/processed/test.jsonl
    - data/processed/train.jsonl
    - src/train.py
    outs:
    - data/processed/test.npz
    - data/processed/train.npz
    - models/indices.pickle
